name : Android Build

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set Up JDK
        uses: actions/setup-java@v1
        working-directory: ./Exercise/FacebookApi
        with:
          java-version: 1.8

      - name: Run Tests
        run: ./gradlew test
        working-directory: ./Exercise/FacebookApi

      - name: Build Project
        run: ./gradlew assemble
        working-directory: ./Exercise/FacebookApi
