name : Android Build

on:
  pull_request:
    paths:
      - 'Project Code/**'
  push:
    paths:
      - 'Project Code/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Run Tests
        working-directory: ./Project Code/SocialPostScheduler
        run: ./gradlew test

      - name: Build Project
        working-directory: ./Project Code/SocialPostScheduler
        run: ./gradlew assemble

      - name: Create APK artifact
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: ./Project Code/SocialPostScheduler/app/build/outputs/apk/debug/app-debug.apk
    
